Dinesh.gurumurthy/set ci 2023
DataDog/opentelemetry-collector-contrib pull request #2894
Opened 2023-02-22 17:11 UTC by dineshg13

**Description:** <Describe what has changed.>

**Link to tracking Issue:** <Issue number if applicable>

**Testing:** <Describe what testing was performed and which tests were added.>

**Documentation:** <Describe the documentation added.>

2023-04-14 17:21 UTC, songy23 approved these changes

2023-04-14 17:21 UTC, songy23 commented on ci/Dockerfile
> +EXPOSE 4317 55680 55679
Expose 4318 (for HTTP) as well?

2023-04-14 17:27 UTC, ancostas requested changes
Can you link a ticket in the title with some description/deliverable?

2023-04-14 17:27 UTC, ancostas commented on .gitlab-ci.yml
> +    - docker push registry.ddbuild.io/ci/opentelemetry-collector-contrib:$TAG
You can remove the script, and add the variables, yielding a common anchor for both:
```
build-ci-image-main:
    <<: *build-ci-image
    script:
        ...

build-ci-image-demo:
    <<: *build-ci-image
    script:
        ...
```

2023-05-08 17:48 UTC, songy23 approved these changes

2023-05-09 07:52 UTC, gbbr commented
Can you please set a title and a description to this PR? In the current form it looks like a WIP draft that is not yet ready for sharing.

2023-05-24 12:30 UTC, gbbr commented
Closing as stale.

2023-05-30 22:10 UTC, bfung commented on .gitlab-ci.yml
> +  CI_PROJECT_NAME: 'dd-trace-demo'
Notes: needs to match https://github.com/DataDog/cloudops/blob/master/AWS/build-stable/ci/opentelemetry-collector-contrib/iam.tf#L3

2023-05-31 13:43 UTC, songy23 reviewed
```
license header checking failed:
make[2]: *** [Makefile.Common:131: checklicense] Error 1
./ci/scripts/ci-deploy-demo.sh
./ci/scripts/ci-deploy-demo.sh
```

Please fix

2023-06-19 09:39 UTC, gbbr approved these changes

2023-06-20 15:20 UTC, merged